project_id = "ksdodojvchiybbqxfhcl"

[functions.enhance-description]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.search]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = true
